#!/usr/bin/env python3
"""
Karos terrain-overrides datapack v2.

Approach: wrap the overworld's `final_density` noise router via Lithostitched
with our `novoatlas:select_by_biome_color` density function. The select samples
the painted biome map at (x,z); inside Nether-color regions it returns the
inlined Nether final_density, inside End-color regions the End final_density,
and outside both falls through to whatever the registry's overworld
final_density currently is — which Tectonic and other mods have wrapped via
their own Lithostitched modifiers, so their terrain enhancements stack
cleanly under ours.

Companion datapack to `karos-datapack/`. Two pieces:
  1. `karos-datapack` (the painted PNG biome source + heightmap + biome map).
  2. `karos-terrain-overrides` (this) — the Lithostitched wrap that swaps
     density inside Nether/End color regions.

Why this works (vs. v1 bbox approach):
  - v1 used bounding boxes via `lithostitched:select` keyed on `axis x/z`.
    That's coordinate-rectangular, doesn't follow the painted blob shape.
  - v2 uses `novoatlas:select_by_biome_color` (added in our Karos fork) which
    samples the actual painted PNG per-block and exact-matches color groups,
    so the boundary follows the painted blob exactly.

Run: python3 season3/scripts/generate-terrain-overrides.py
"""
from __future__ import annotations
import json
from pathlib import Path

import numpy as np
from PIL import Image

REPO = Path(__file__).resolve().parents[2]
SRC_BIOME_MAP = REPO / "season3" / "karos-datapack" / "data/caero_karos/novoatlas/biome_map/karos.png"
DP = REPO / "season3" / "karos-terrain-overrides"
NAMESPACE = "caero_karos_terrain"

# All shade variants of the Nether and End zones, generated by
# generate-karos-datapack.py's shade_variants() with offsets 0..N-1.
NETHER_RGBS = [(236,1,1), (237,2,2), (238,3,3), (239,4,4), (240,5,5)]
END_RGBS    = [(223,8,238), (224,9,239), (225,10,240), (226,11,241)]


def hex_color(rgb: tuple[int, int, int]) -> str:
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def write_final_density_wrap() -> dict:
    """
    Lithostitched modifier: wrap_noise_router on final_density.
    The wrapper is novoatlas:select_by_biome_color whose fallback is
    lithostitched:wrapped_marker (the original final_density, which Tectonic
    has already wrapped). Inside Nether/End color regions, return the
    inlined nether/end final density from karos-datapack.
    """
    return {
        "type": "lithostitched:wrap_noise_router",
        # High priority so we wrap LAST → outermost. If Tectonic's wrap
        # were applied outside ours, it would amplify our nether_final
        # density into mountain-scale terrain (Y=320+ instead of Y=63 roof).
        "priority": 10000,
        "dimension": "minecraft:overworld",
        "target": "final_density",
        "wrapper_function": {
            "type": "novoatlas:select_by_biome_color",
            "map_info": "caero_karos:karos",
            "fallback": {"type": "lithostitched:wrapped_marker"},
            "selections": [
                {
                    "colors": [hex_color(c) for c in NETHER_RGBS],
                    "function": "caero_karos:nether_final",
                },
                {
                    "colors": [hex_color(c) for c in END_RGBS],
                    "function": "caero_karos:end_final",
                },
            ],
        },
    }


def main():
    DP.mkdir(parents=True, exist_ok=True)
    base = DP / "data" / NAMESPACE / "lithostitched" / "worldgen_modifier"
    base.mkdir(parents=True, exist_ok=True)

    # Wipe stale modifiers from v1 (bbox-based density wraps + surface rules)
    for stale in ("wrap_final_density.json", "wrap_initial_density.json",
                  "nether_surface_rule.json", "end_surface_rule.json"):
        (base / stale).unlink(missing_ok=True)

    (base / "final_density_swap.json").write_text(
        json.dumps(write_final_density_wrap(), indent=2) + "\n")

    pack_meta = {
        "pack": {
            "pack_format": 48,
            "description": "Caero Karos terrain overrides — Nether/End density wrap.",
        }
    }
    (DP / "pack.mcmeta").write_text(json.dumps(pack_meta, indent=2) + "\n")

    print("Written:")
    for p in sorted(DP.rglob("*.json")) + [DP / "pack.mcmeta"]:
        print(f"  {p.relative_to(REPO)}")


if __name__ == "__main__":
    main()
